Feature/tab
yevhentretiakov/HTabView pull request #1
Opened 2022-08-17 11:53 UTC by yevhentretiakov

Created reusable tabview with possibility to set list of tabs and indicator color.

2022-08-22 07:42 UTC, Nikitax23 requested changes
Неплохо. 
Но лично я нахожу лишним работу с констрейнтами. Это можно сделать на фреймах, и будет меньше нагруженность и меньше манипуляций.
Рекомендую отреагировать на оставленные комментарии, и улучшить код. 
А после этого, когда смержишь - создать новую ветку от смерженного дева, и переделать на фреймы. 
Посмотреть на обе версии, и подумать, как тебе больше нравится.

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Application/SceneDelegate.swift
> +    private func createRootView(scene: UIScene) {
`createRootView` => `setRootView`

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Extensions/String+Extensions.swift
> +        return self.size(withAttributes: [NSAttributedString.Key.font : UIFont.systemFont(ofSize: 17)]).width
не думаю, что это хорошая идея. 
Лучше иметь это в виде функции, и передавать туда шрифт. 
а в качестве дефолтного параметра уже иметь твой `.systemFont(ofSize: 17)`

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/Controller/TabListtViewController.swift
> +
лишний отступ

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/Controller/TabListtViewController.swift
> +
лишний отступ

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/Controller/TabListtViewController.swift
> +        var tabs = ["work", "home", "family", "home", "family", "home", "family", "work", "home", "home", "family", "home", "family", "work", "home"]
смысл создавать var , если один раз инитим и не меняем значение?

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +        let scrollView = UIScrollView()
не уверен, зачем тебе здесь дополнительный скролл вью, если он и так есть на коллекции

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +    private var tabs: [String]!
```
private var tabs: [String]!
private var indicatorColor: UIColor!
```

здесь можно не форсить, так как на ините ты инициализируешь эти свойства.

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +        layoutCollectionView()
`layoutCollectionView()`
это можно внутрь setupCollectionView положить

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +            if let width = sizeForTab(at: 0)?.width {
у тебя работа с индикатором должна быть вынесена в один метод, и переиспользоваться

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +            collectionView.selectItem(at: IndexPath(item: index, section: 0),
когда выбираешь какой-то таб, хорошо бы скроллить коллекцию к этому айтему

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +            if tabs.count <= 3 {
`3` - что такое 3 ? мне непонятно. это magic number

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +        cell.indicatorColor = indicatorColor
1) 
```
let tab = tabs[indexPath.row]
cell.set(label: tab)
```

=> 

```
let tabTitle = tabs[indexPath.row]
cell.configure(with: tabTitle)
```

2) indicatorColor свойство должно быть приватным, и инититься из configure метода

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +                self.chevronLeadingConstraint.constant = cell.frame.origin.x
вот у тебя должен быть метод , который работает с индикатором. и здесь его нужно вызывать) 

и он ничего не должен знать про ячейку

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +        return sizeForTab(at: indexPath.row) ?? CGSize(width: 0, height: 0)
`CGSize(width: 0, height: 0)` можно заменить на `.zero`

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +    static let reuseID = "HTabViewCell"
идентификатор можно получить программно

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +    var indicatorColor: UIColor = .blue {
`var indicatorColor` => `private var indicatorColor`

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +    func set(label: String) {
тут уже прокомментил в файле вьюхи

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +            if self.isSelected {
1) можно заменить `if/else` на тернарный оператор
2) .label - это системный цвет. ты смотрел, как это будет выглядеть в разных темах iOS ? 
Нужно быть осторожными с такими системными цветами, которые подстраиваются сами под тему iOS. Это может в будущем быть проблемой для коммерческого приложения.

2022-08-22 07:42 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +        textLabel.translatesAutoresizingMaskIntoConstraints = false
```
textLabel.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            textLabel.centerXAnchor.constraint(equalTo: self.centerXAnchor),
            textLabel.centerYAnchor.constraint(equalTo: self.centerYAnchor)
        ])
```

можно кстати такое вынести в экстеншн

2022-08-22 09:56 UTC, yevhentretiakov commented on HTabView/HTabView/Modules/TabList/Controller/TabListtViewController.swift
> +        var tabs = ["work", "home", "family", "home", "family", "home", "family", "work", "home", "home", "family", "home", "family", "work", "home"]
Создал для читаемости, к примеру если большой массив, то длинная строка получается и не очень удобно. Правильнее конечно было через let. 

Или лучше такие переменные не создавать, а целиком вставлять в случае если эта переменная нигде потом еще не будет использоваться/меняться?

2022-08-23 07:43 UTC, yevhentretiakov commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +    private var tabs: [String]!
Если убираю форс, то выходит ошибка в инициализаторе `Property 'self.tabs' not initialized at super.init call`

2022-08-23 12:24 UTC, yevhentretiakov commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +        let scrollView = UIScrollView()
Я пробовал вставить этот индикатор в коллекцию, но как не крутил это не давало нужного результата, чтобы именно при скролле коллекции этот индикатор тоже скролился вместе с коллекцией. 

Попробовал сделать отдельный скролл вью и там сделать уже двигать contentOffset и получилось все как надо.

2022-08-29 21:20 UTC, Nikitax23 requested changes
есть, что оптимизировать

2022-08-29 21:20 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabView.swift
> +                self.layoutIfNeeded()
`self.layoutIfNeeded()`
это вызывать не нужно здесь больше, так как ты не используешь констрейнты здесь.

2022-08-29 21:20 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +
лишний пробел

2022-08-29 21:20 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +    func configure(with tabTitle: String, and indicatorActiveColor: UIColor, and indicatorInactiveColor: UIColor) {
`func configure(with tabTitle: String, and indicatorActiveColor: UIColor, and indicatorInactiveColor: UIColor) {`
здесь не нужно `and ... and ` 
можешь вообще убрать эти слова

2022-09-01 07:03 UTC, Nikitax23 approved these changes
Молодец! 
Поправь один момент самостоятельно, и можно мержить!

2022-09-01 07:03 UTC, Nikitax23 commented on HTabView/HTabView/Modules/TabList/CustomUI/HTabView/HTabViewCell.swift
> +    func configure(with tabTitle: String, _ indicatorActiveColor: UIColor, _ indicatorInactiveColor: UIColor) {
`func configure(with tabTitle: String, _ indicatorActiveColor: UIColor, _ indicatorInactiveColor: UIColor)`

а зачем ты здесь подобавлял _ везде? 
это как раз должны быть именованные параметры здесь

2022-09-01 07:16 UTC, merged